server:
  port: 8080

spring:
  application:
    name: crm-coursework

  datasource:
    url: jdbc:postgresql://localhost:5432/crm_db
    username: postgres
    password: 242368
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml